package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1



/**
 * Advogado generated by hbm2java
 */
public class Advogado  implements java.io.Serializable {


     private Integer idAdvogado;
     private Pessoafisica pessoafisica;
     private Usuario usuario;
     private String oab;

    public Advogado() {
    }

    public Advogado(Pessoafisica pessoafisica, Usuario usuario, String oab) {
       this.pessoafisica = pessoafisica;
       this.usuario = usuario;
       this.oab = oab;
    }
   
    public Integer getIdAdvogado() {
        return this.idAdvogado;
    }
    
    public void setIdAdvogado(Integer idAdvogado) {
        this.idAdvogado = idAdvogado;
    }
    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }
    
    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getOab() {
        return this.oab;
    }
    
    public void setOab(String oab) {
        this.oab = oab;
    }




}


