package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Audiencia generated by hbm2java
 */
public class Audiencia  implements java.io.Serializable {


     private Integer idAudiencia;
     private Processo processo;
     private Date dataAudiencia;

    public Audiencia() {
    }

    public Audiencia(Processo processo, Date dataAudiencia) {
       this.processo = processo;
       this.dataAudiencia = dataAudiencia;
    }
   
    public Integer getIdAudiencia() {
        return this.idAudiencia;
    }
    
    public void setIdAudiencia(Integer idAudiencia) {
        this.idAudiencia = idAudiencia;
    }
    public Processo getProcesso() {
        return this.processo;
    }
    
    public void setProcesso(Processo processo) {
        this.processo = processo;
    }
    public Date getDataAudiencia() {
        return this.dataAudiencia;
    }
    
    public void setDataAudiencia(Date dataAudiencia) {
        this.dataAudiencia = dataAudiencia;
    }




}


