package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private Integer idbairro;
     private Cidade cidade;
     private String nomeBairro;
     private Set logradouros = new HashSet(0);

    public Bairro() {
    }

	
    public Bairro(Cidade cidade, String nomeBairro) {
        this.cidade = cidade;
        this.nomeBairro = nomeBairro;
    }
    public Bairro(Cidade cidade, String nomeBairro, Set logradouros) {
       this.cidade = cidade;
       this.nomeBairro = nomeBairro;
       this.logradouros = logradouros;
    }
   
    public Integer getIdbairro() {
        return this.idbairro;
    }
    
    public void setIdbairro(Integer idbairro) {
        this.idbairro = idbairro;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getNomeBairro() {
        return this.nomeBairro;
    }
    
    public void setNomeBairro(String nomeBairro) {
        this.nomeBairro = nomeBairro;
    }
    public Set getLogradouros() {
        return this.logradouros;
    }
    
    public void setLogradouros(Set logradouros) {
        this.logradouros = logradouros;
    }




}


