package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer idCidade;
     private Uf uf;
     private String nomeCidade;
     private Set bairros = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(Uf uf, String nomeCidade) {
        this.uf = uf;
        this.nomeCidade = nomeCidade;
    }
    public Cidade(Uf uf, String nomeCidade, Set bairros) {
       this.uf = uf;
       this.nomeCidade = nomeCidade;
       this.bairros = bairros;
    }
   
    public Integer getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(Integer idCidade) {
        this.idCidade = idCidade;
    }
    public Uf getUf() {
        return this.uf;
    }
    
    public void setUf(Uf uf) {
        this.uf = uf;
    }
    public String getNomeCidade() {
        return this.nomeCidade;
    }
    
    public void setNomeCidade(String nomeCidade) {
        this.nomeCidade = nomeCidade;
    }
    public Set getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Set bairros) {
        this.bairros = bairros;
    }




}


