package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Emails generated by hbm2java
 */
public class Emails  implements java.io.Serializable {


     private Integer idEmails;
     private String email;
     private Set pessoajuridicas = new HashSet(0);
     private Set pessoafisicas = new HashSet(0);

    public Emails() {
    }

	
    public Emails(String email) {
        this.email = email;
    }
    public Emails(String email, Set pessoajuridicas, Set pessoafisicas) {
       this.email = email;
       this.pessoajuridicas = pessoajuridicas;
       this.pessoafisicas = pessoafisicas;
    }
   
    public Integer getIdEmails() {
        return this.idEmails;
    }
    
    public void setIdEmails(Integer idEmails) {
        this.idEmails = idEmails;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPessoajuridicas() {
        return this.pessoajuridicas;
    }
    
    public void setPessoajuridicas(Set pessoajuridicas) {
        this.pessoajuridicas = pessoajuridicas;
    }
    public Set getPessoafisicas() {
        return this.pessoafisicas;
    }
    
    public void setPessoafisicas(Set pessoafisicas) {
        this.pessoafisicas = pessoafisicas;
    }




}


