package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private Logradouro logradouro;
     private int ncasa;
     private Set pessoafisicas = new HashSet(0);
     private Set pessoajuridicas = new HashSet(0);

    public Endereco() {
    }

	
    public Endereco(Logradouro logradouro, int ncasa) {
        this.logradouro = logradouro;
        this.ncasa = ncasa;
    }
    public Endereco(Logradouro logradouro, int ncasa, Set pessoafisicas, Set pessoajuridicas) {
       this.logradouro = logradouro;
       this.ncasa = ncasa;
       this.pessoafisicas = pessoafisicas;
       this.pessoajuridicas = pessoajuridicas;
    }
   
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }
    public Logradouro getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Logradouro logradouro) {
        this.logradouro = logradouro;
    }
    public int getNcasa() {
        return this.ncasa;
    }
    
    public void setNcasa(int ncasa) {
        this.ncasa = ncasa;
    }
    public Set getPessoafisicas() {
        return this.pessoafisicas;
    }
    
    public void setPessoafisicas(Set pessoafisicas) {
        this.pessoafisicas = pessoafisicas;
    }
    public Set getPessoajuridicas() {
        return this.pessoajuridicas;
    }
    
    public void setPessoajuridicas(Set pessoajuridicas) {
        this.pessoajuridicas = pessoajuridicas;
    }




}


