package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String nomeEstato;
     private Set processos = new HashSet(0);
     private Set estadosForEstadoIdEstado = new HashSet(0);
     private Set estadosForEstadoRelacionado = new HashSet(0);

    public Estado() {
    }

	
    public Estado(String nomeEstato) {
        this.nomeEstato = nomeEstato;
    }
    public Estado(String nomeEstato, Set processos, Set estadosForEstadoIdEstado, Set estadosForEstadoRelacionado) {
       this.nomeEstato = nomeEstato;
       this.processos = processos;
       this.estadosForEstadoIdEstado = estadosForEstadoIdEstado;
       this.estadosForEstadoRelacionado = estadosForEstadoRelacionado;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNomeEstato() {
        return this.nomeEstato;
    }
    
    public void setNomeEstato(String nomeEstato) {
        this.nomeEstato = nomeEstato;
    }
    public Set getProcessos() {
        return this.processos;
    }
    
    public void setProcessos(Set processos) {
        this.processos = processos;
    }
    public Set getEstadosForEstadoIdEstado() {
        return this.estadosForEstadoIdEstado;
    }
    
    public void setEstadosForEstadoIdEstado(Set estadosForEstadoIdEstado) {
        this.estadosForEstadoIdEstado = estadosForEstadoIdEstado;
    }
    public Set getEstadosForEstadoRelacionado() {
        return this.estadosForEstadoRelacionado;
    }
    
    public void setEstadosForEstadoRelacionado(Set estadosForEstadoRelacionado) {
        this.estadosForEstadoRelacionado = estadosForEstadoRelacionado;
    }




}


