package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Logradouro generated by hbm2java
 */
public class Logradouro  implements java.io.Serializable {


     private int cep;
     private Bairro bairro;
     private String nomeLogradouro;
     private Set enderecos = new HashSet(0);

    public Logradouro() {
    }

	
    public Logradouro(int cep, Bairro bairro, String nomeLogradouro) {
        this.cep = cep;
        this.bairro = bairro;
        this.nomeLogradouro = nomeLogradouro;
    }
    public Logradouro(int cep, Bairro bairro, String nomeLogradouro, Set enderecos) {
       this.cep = cep;
       this.bairro = bairro;
       this.nomeLogradouro = nomeLogradouro;
       this.enderecos = enderecos;
    }
   
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public String getNomeLogradouro() {
        return this.nomeLogradouro;
    }
    
    public void setNomeLogradouro(String nomeLogradouro) {
        this.nomeLogradouro = nomeLogradouro;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }




}


