package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pagamentoprazo generated by hbm2java
 */
public class Pagamentoprazo  implements java.io.Serializable {


     private int pagamentoIdPagamento;
     private Pagamento pagamento;
     private float valorParcela;
     private String modoPagamento;
     private Set parcelas = new HashSet(0);

    public Pagamentoprazo() {
    }

	
    public Pagamentoprazo(Pagamento pagamento, float valorParcela, String modoPagamento) {
        this.pagamento = pagamento;
        this.valorParcela = valorParcela;
        this.modoPagamento = modoPagamento;
    }
    public Pagamentoprazo(Pagamento pagamento, float valorParcela, String modoPagamento, Set parcelas) {
       this.pagamento = pagamento;
       this.valorParcela = valorParcela;
       this.modoPagamento = modoPagamento;
       this.parcelas = parcelas;
    }
   
    public int getPagamentoIdPagamento() {
        return this.pagamentoIdPagamento;
    }
    
    public void setPagamentoIdPagamento(int pagamentoIdPagamento) {
        this.pagamentoIdPagamento = pagamentoIdPagamento;
    }
    public Pagamento getPagamento() {
        return this.pagamento;
    }
    
    public void setPagamento(Pagamento pagamento) {
        this.pagamento = pagamento;
    }
    public float getValorParcela() {
        return this.valorParcela;
    }
    
    public void setValorParcela(float valorParcela) {
        this.valorParcela = valorParcela;
    }
    public String getModoPagamento() {
        return this.modoPagamento;
    }
    
    public void setModoPagamento(String modoPagamento) {
        this.modoPagamento = modoPagamento;
    }
    public Set getParcelas() {
        return this.parcelas;
    }
    
    public void setParcelas(Set parcelas) {
        this.parcelas = parcelas;
    }




}


