package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento  implements java.io.Serializable {


     private int idPagamento;
     private double valorTotal;
     private Date dataPagamento;
     private Pagamentoprazo pagamentoprazo;
     private Set processos = new HashSet(0);

    public Pagamento() {
    }

	
    public Pagamento(int idPagamento, double valorTotal, Date dataPagamento) {
        this.idPagamento = idPagamento;
        this.valorTotal = valorTotal;
        this.dataPagamento = dataPagamento;
    }
    public Pagamento(int idPagamento, double valorTotal, Date dataPagamento, Pagamentoprazo pagamentoprazo, Set processos) {
       this.idPagamento = idPagamento;
       this.valorTotal = valorTotal;
       this.dataPagamento = dataPagamento;
       this.pagamentoprazo = pagamentoprazo;
       this.processos = processos;
    }
   
    public int getIdPagamento() {
        return this.idPagamento;
    }
    
    public void setIdPagamento(int idPagamento) {
        this.idPagamento = idPagamento;
    }
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Date getDataPagamento() {
        return this.dataPagamento;
    }
    
    public void setDataPagamento(Date dataPagamento) {
        this.dataPagamento = dataPagamento;
    }
    public Pagamentoprazo getPagamentoprazo() {
        return this.pagamentoprazo;
    }
    
    public void setPagamentoprazo(Pagamentoprazo pagamentoprazo) {
        this.pagamentoprazo = pagamentoprazo;
    }
    public Set getProcessos() {
        return this.processos;
    }
    
    public void setProcessos(Set processos) {
        this.processos = processos;
    }




}


