package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import Dominio.Endereco;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoafisica generated by hbm2java
 */
public class Pessoafisica  implements java.io.Serializable {


     private Integer idPessoaFisica;
     private Emails emails;
     private Endereco endereco;
     private Telefones telefones;
     private String nomePrssoaFisica;
     private String site;
     private int cpf;
     private Date dataNascimento;
     private String estadoCivil;
     private String naturalidade;
     private String nacionalidade;
     private Set advogados = new HashSet(0);
     private Set processos = new HashSet(0);

    public Pessoafisica() {
    }

	
    public Pessoafisica(Emails emails, Endereco endereco, Telefones telefones, String nomePrssoaFisica, int cpf, Date dataNascimento, String estadoCivil, String naturalidade, String nacionalidade) {
        this.emails = emails;
        this.endereco = endereco;
        this.telefones = telefones;
        this.nomePrssoaFisica = nomePrssoaFisica;
        this.cpf = cpf;
        this.dataNascimento = dataNascimento;
        this.estadoCivil = estadoCivil;
        this.naturalidade = naturalidade;
        this.nacionalidade = nacionalidade;
    }
    public Pessoafisica(Emails emails, Endereco endereco, Telefones telefones, String nomePrssoaFisica, String site, int cpf, Date dataNascimento, String estadoCivil, String naturalidade, String nacionalidade, Set advogados, Set processos) {
       this.emails = emails;
       this.endereco = endereco;
       this.telefones = telefones;
       this.nomePrssoaFisica = nomePrssoaFisica;
       this.site = site;
       this.cpf = cpf;
       this.dataNascimento = dataNascimento;
       this.estadoCivil = estadoCivil;
       this.naturalidade = naturalidade;
       this.nacionalidade = nacionalidade;
       this.advogados = advogados;
       this.processos = processos;
    }
   
    public Integer getIdPessoaFisica() {
        return this.idPessoaFisica;
    }
    
    public void setIdPessoaFisica(Integer idPessoaFisica) {
        this.idPessoaFisica = idPessoaFisica;
    }
    public Emails getEmails() {
        return this.emails;
    }
    
    public void setEmails(Emails emails) {
        this.emails = emails;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefones getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Telefones telefones) {
        this.telefones = telefones;
    }
    public String getNomePrssoaFisica() {
        return this.nomePrssoaFisica;
    }
    
    public void setNomePrssoaFisica(String nomePrssoaFisica) {
        this.nomePrssoaFisica = nomePrssoaFisica;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public int getCpf() {
        return this.cpf;
    }
    
    public void setCpf(int cpf) {
        this.cpf = cpf;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNaturalidade() {
        return this.naturalidade;
    }
    
    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
    public Set getAdvogados() {
        return this.advogados;
    }
    
    public void setAdvogados(Set advogados) {
        this.advogados = advogados;
    }
    public Set getProcessos() {
        return this.processos;
    }
    
    public void setProcessos(Set processos) {
        this.processos = processos;
    }




}


