package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import Dominio.Endereco;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoajuridica generated by hbm2java
 */
public class Pessoajuridica  implements java.io.Serializable {


     private Integer idPessoaJuridica;
     private Emails emails;
     private Endereco endereco;
     private Telefones telefones;
     private String nomePessoaJuridica;
     private String site;
     private int cnpj;
     private String razaoSocial;
     private String inscricaoEstadual;
     private String inscricaoMunicipal;
     private Set processos = new HashSet(0);

    public Pessoajuridica() {
    }

	
    public Pessoajuridica(Emails emails, Endereco endereco, Telefones telefones, String nomePessoaJuridica, int cnpj, String razaoSocial, String inscricaoEstadual, String inscricaoMunicipal) {
        this.emails = emails;
        this.endereco = endereco;
        this.telefones = telefones;
        this.nomePessoaJuridica = nomePessoaJuridica;
        this.cnpj = cnpj;
        this.razaoSocial = razaoSocial;
        this.inscricaoEstadual = inscricaoEstadual;
        this.inscricaoMunicipal = inscricaoMunicipal;
    }
    public Pessoajuridica(Emails emails, Endereco endereco, Telefones telefones, String nomePessoaJuridica, String site, int cnpj, String razaoSocial, String inscricaoEstadual, String inscricaoMunicipal, Set processos) {
       this.emails = emails;
       this.endereco = endereco;
       this.telefones = telefones;
       this.nomePessoaJuridica = nomePessoaJuridica;
       this.site = site;
       this.cnpj = cnpj;
       this.razaoSocial = razaoSocial;
       this.inscricaoEstadual = inscricaoEstadual;
       this.inscricaoMunicipal = inscricaoMunicipal;
       this.processos = processos;
    }
   
    public Integer getIdPessoaJuridica() {
        return this.idPessoaJuridica;
    }
    
    public void setIdPessoaJuridica(Integer idPessoaJuridica) {
        this.idPessoaJuridica = idPessoaJuridica;
    }
    public Emails getEmails() {
        return this.emails;
    }
    
    public void setEmails(Emails emails) {
        this.emails = emails;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefones getTelefones() {
        return this.telefones;
    }
    
    public void setTelefones(Telefones telefones) {
        this.telefones = telefones;
    }
    public String getNomePessoaJuridica() {
        return this.nomePessoaJuridica;
    }
    
    public void setNomePessoaJuridica(String nomePessoaJuridica) {
        this.nomePessoaJuridica = nomePessoaJuridica;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public int getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(int cnpj) {
        this.cnpj = cnpj;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getInscricaoEstadual() {
        return this.inscricaoEstadual;
    }
    
    public void setInscricaoEstadual(String inscricaoEstadual) {
        this.inscricaoEstadual = inscricaoEstadual;
    }
    public String getInscricaoMunicipal() {
        return this.inscricaoMunicipal;
    }
    
    public void setInscricaoMunicipal(String inscricaoMunicipal) {
        this.inscricaoMunicipal = inscricaoMunicipal;
    }
    public Set getProcessos() {
        return this.processos;
    }
    
    public void setProcessos(Set processos) {
        this.processos = processos;
    }




}


