package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1



/**
 * ProcessoadvogadoId generated by hbm2java
 */
public class ProcessoadvogadoId  implements java.io.Serializable {


     private int advogadoPessoaJuridicaIdPessoaJuridica;
     private int processoIdProcesso;

    public ProcessoadvogadoId() {
    }

    public ProcessoadvogadoId(int advogadoPessoaJuridicaIdPessoaJuridica, int processoIdProcesso) {
       this.advogadoPessoaJuridicaIdPessoaJuridica = advogadoPessoaJuridicaIdPessoaJuridica;
       this.processoIdProcesso = processoIdProcesso;
    }
   
    public int getAdvogadoPessoaJuridicaIdPessoaJuridica() {
        return this.advogadoPessoaJuridicaIdPessoaJuridica;
    }
    
    public void setAdvogadoPessoaJuridicaIdPessoaJuridica(int advogadoPessoaJuridicaIdPessoaJuridica) {
        this.advogadoPessoaJuridicaIdPessoaJuridica = advogadoPessoaJuridicaIdPessoaJuridica;
    }
    public int getProcessoIdProcesso() {
        return this.processoIdProcesso;
    }
    
    public void setProcessoIdProcesso(int processoIdProcesso) {
        this.processoIdProcesso = processoIdProcesso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProcessoadvogadoId) ) return false;
		 ProcessoadvogadoId castOther = ( ProcessoadvogadoId ) other; 
         
		 return (this.getAdvogadoPessoaJuridicaIdPessoaJuridica()==castOther.getAdvogadoPessoaJuridicaIdPessoaJuridica())
 && (this.getProcessoIdProcesso()==castOther.getProcessoIdProcesso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAdvogadoPessoaJuridicaIdPessoaJuridica();
         result = 37 * result + this.getProcessoIdProcesso();
         return result;
   }   


}


