package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Processo generated by hbm2java
 */
public class Processo  implements java.io.Serializable {


     private Integer idProcesso;
     private Estado estado;
     private Pagamento pagamento;
     private int numeroProcesso;
     private String titulo;
     private String pasta;
     private String justica;
     private String instancia;
     private String orgao;
     private String valorProcesso;
     private String descricao;
     private String acao;
     private int pagamentoIdPagamento;
     private Set audiencias = new HashSet(0);
     private Set pessoajuridicas = new HashSet(0);
     private Set processoadvogados = new HashSet(0);
     private Set pessoafisicas = new HashSet(0);

    public Processo() {
    }

	
    public Processo(Estado estado, Pagamento pagamento, int numeroProcesso, String titulo, String pasta, String justica, String instancia, String orgao, String valorProcesso, String descricao, String acao, int pagamentoIdPagamento) {
        this.estado = estado;
        this.pagamento = pagamento;
        this.numeroProcesso = numeroProcesso;
        this.titulo = titulo;
        this.pasta = pasta;
        this.justica = justica;
        this.instancia = instancia;
        this.orgao = orgao;
        this.valorProcesso = valorProcesso;
        this.descricao = descricao;
        this.acao = acao;
        this.pagamentoIdPagamento = pagamentoIdPagamento;
    }
    public Processo(Estado estado, Pagamento pagamento, int numeroProcesso, String titulo, String pasta, String justica, String instancia, String orgao, String valorProcesso, String descricao, String acao, int pagamentoIdPagamento, Set audiencias, Set pessoajuridicas, Set processoadvogados, Set pessoafisicas) {
       this.estado = estado;
       this.pagamento = pagamento;
       this.numeroProcesso = numeroProcesso;
       this.titulo = titulo;
       this.pasta = pasta;
       this.justica = justica;
       this.instancia = instancia;
       this.orgao = orgao;
       this.valorProcesso = valorProcesso;
       this.descricao = descricao;
       this.acao = acao;
       this.pagamentoIdPagamento = pagamentoIdPagamento;
       this.audiencias = audiencias;
       this.pessoajuridicas = pessoajuridicas;
       this.processoadvogados = processoadvogados;
       this.pessoafisicas = pessoafisicas;
    }
   
    public Integer getIdProcesso() {
        return this.idProcesso;
    }
    
    public void setIdProcesso(Integer idProcesso) {
        this.idProcesso = idProcesso;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Pagamento getPagamento() {
        return this.pagamento;
    }
    
    public void setPagamento(Pagamento pagamento) {
        this.pagamento = pagamento;
    }
    public int getNumeroProcesso() {
        return this.numeroProcesso;
    }
    
    public void setNumeroProcesso(int numeroProcesso) {
        this.numeroProcesso = numeroProcesso;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getPasta() {
        return this.pasta;
    }
    
    public void setPasta(String pasta) {
        this.pasta = pasta;
    }
    public String getJustica() {
        return this.justica;
    }
    
    public void setJustica(String justica) {
        this.justica = justica;
    }
    public String getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(String instancia) {
        this.instancia = instancia;
    }
    public String getOrgao() {
        return this.orgao;
    }
    
    public void setOrgao(String orgao) {
        this.orgao = orgao;
    }
    public String getValorProcesso() {
        return this.valorProcesso;
    }
    
    public void setValorProcesso(String valorProcesso) {
        this.valorProcesso = valorProcesso;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }
    public int getPagamentoIdPagamento() {
        return this.pagamentoIdPagamento;
    }
    
    public void setPagamentoIdPagamento(int pagamentoIdPagamento) {
        this.pagamentoIdPagamento = pagamentoIdPagamento;
    }
    public Set getAudiencias() {
        return this.audiencias;
    }
    
    public void setAudiencias(Set audiencias) {
        this.audiencias = audiencias;
    }
    public Set getPessoajuridicas() {
        return this.pessoajuridicas;
    }
    
    public void setPessoajuridicas(Set pessoajuridicas) {
        this.pessoajuridicas = pessoajuridicas;
    }
    public Set getProcessoadvogados() {
        return this.processoadvogados;
    }
    
    public void setProcessoadvogados(Set processoadvogados) {
        this.processoadvogados = processoadvogados;
    }
    public Set getPessoafisicas() {
        return this.pessoafisicas;
    }
    
    public void setPessoafisicas(Set pessoafisicas) {
        this.pessoafisicas = pessoafisicas;
    }




}


