package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Telefones generated by hbm2java
 */
public class Telefones  implements java.io.Serializable {


     private Integer idtelefones;
     private int numero;
     private Set pessoajuridicas = new HashSet(0);
     private Set pessoafisicas = new HashSet(0);

    public Telefones() {
    }

	
    public Telefones(int numero) {
        this.numero = numero;
    }
    public Telefones(int numero, Set pessoajuridicas, Set pessoafisicas) {
       this.numero = numero;
       this.pessoajuridicas = pessoajuridicas;
       this.pessoafisicas = pessoafisicas;
    }
   
    public Integer getIdtelefones() {
        return this.idtelefones;
    }
    
    public void setIdtelefones(Integer idtelefones) {
        this.idtelefones = idtelefones;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Set getPessoajuridicas() {
        return this.pessoajuridicas;
    }
    
    public void setPessoajuridicas(Set pessoajuridicas) {
        this.pessoajuridicas = pessoajuridicas;
    }
    public Set getPessoafisicas() {
        return this.pessoafisicas;
    }
    
    public void setPessoafisicas(Set pessoafisicas) {
        this.pessoafisicas = pessoafisicas;
    }




}


