package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Uf generated by hbm2java
 */
public class Uf  implements java.io.Serializable {


     private Integer idUf;
     private String nomeUf;
     private Set cidades = new HashSet(0);

    public Uf() {
    }

	
    public Uf(String nomeUf) {
        this.nomeUf = nomeUf;
    }
    public Uf(String nomeUf, Set cidades) {
       this.nomeUf = nomeUf;
       this.cidades = cidades;
    }
   
    public Integer getIdUf() {
        return this.idUf;
    }
    
    public void setIdUf(Integer idUf) {
        this.idUf = idUf;
    }
    public String getNomeUf() {
        return this.nomeUf;
    }
    
    public void setNomeUf(String nomeUf) {
        this.nomeUf = nomeUf;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


