package newpackage;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String login;
     private String senha;
     private Set advogados = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String login, String senha) {
        this.login = login;
        this.senha = senha;
    }
    public Usuario(String login, String senha, Set advogados) {
       this.login = login;
       this.senha = senha;
       this.advogados = advogados;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getAdvogados() {
        return this.advogados;
    }
    
    public void setAdvogados(Set advogados) {
        this.advogados = advogados;
    }




}


