package Dominio;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.*;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(schema = "ProjectPOO2")
public class Endereco  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int idEndereco;
    
    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)    
    @JoinColumn(name = "cep", insertable = true, updatable = true)   
    @Fetch(FetchMode.JOIN)
    @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
    private Logradouro logradouro;
    
    @Column(nullable = false)
    private int ncasa;
    
    @OneToMany(mappedBy = "endereco", fetch = FetchType.LAZY)
    private Collection<PessoaFisica> pessoa;

    public Endereco() {
    }
    
	
    public Endereco(Logradouro logradouro, int ncasa) {
        this.logradouro = logradouro;
        this.ncasa = ncasa;
    }

    public Endereco(int idEndereco, Logradouro logradouro, int ncasa, Collection<PessoaFisica> pessoa) {
        this.idEndereco = idEndereco;
        this.logradouro = logradouro;
        this.ncasa = ncasa;
        this.pessoa = pessoa;
    }

    
  
    public int getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(int idEndereco) {
        this.idEndereco = idEndereco;
    }
    public Logradouro getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Logradouro logradouro) {
        this.logradouro = logradouro;
    }
    public int getNcasa() {
        return this.ncasa;
    }
    
    public void setNcasa(int ncasa) {
        this.ncasa = ncasa;
    }

    public Collection<PessoaFisica> getPessoa() {
        return pessoa;
    }

    public void setPessoa(Collection<PessoaFisica> pessoa) {
        this.pessoa = pessoa;
    }
   

}


