package Dominio;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.*;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Logradouro generated by hbm2java
 */
@Entity
@Table(schema = "ProjectPOO2")
public class Logradouro  implements java.io.Serializable {

     @Id    
     private int cep;
     
     @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)    
     @JoinColumn(name = "idBairro", insertable = true, updatable = true)
     @Fetch(FetchMode.JOIN)
     @Cascade(org.hibernate.annotations.CascadeType.SAVE_UPDATE)
     private Bairro bairro;
     
     @Column(length = 45, nullable = false)
     private String nomeLogradouro;
     
     @OneToMany(mappedBy = "logradouro", fetch = FetchType.LAZY)
     private Collection<Endereco> enderecos;

    public Logradouro() {
    }
    

    public Logradouro(int cep, Bairro bairro, String nomeLogradouro) {
        this.cep = cep;
        this.bairro = bairro;
        this.nomeLogradouro = nomeLogradouro;
    }
    
    public Logradouro(int cep, Bairro bairro, String nomeLogradouro, Collection<Endereco> enderecos) {
        this.cep = cep;
        this.bairro = bairro;
        this.nomeLogradouro = nomeLogradouro;
        this.enderecos = enderecos;
    }

   
   
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public String getNomeLogradouro() {
        return this.nomeLogradouro;
    }
    
    public void setNomeLogradouro(String nomeLogradouro) {
        this.nomeLogradouro = nomeLogradouro;
    }

    public Collection<Endereco> getEnderecos() {
        return enderecos;
    }

    public void setEnderecos(Collection<Endereco> enderecos) {
        this.enderecos = enderecos;
    }
}


