package Dominio;
// Generated 19/06/2017 16:21:07 by Hibernate Tools 4.3.1


import java.util.Collection;
import javax.persistence.*;

/**
 * Uf generated by hbm2java
 */
@Entity
@Table(schema = "ProjectPOO2")
public class Uf  implements java.io.Serializable {

    @Id     
    @GeneratedValue(strategy = GenerationType.AUTO)
     private int idUf;
    
     @Column(length = 45, nullable = false)
     private String nomeUf;
     
     @OneToMany(mappedBy = "idCidade", fetch = FetchType.LAZY)
     private Collection<Cidade> cidades;

    public Uf() {
    }

	
    public Uf(String nomeUf) {
        this.nomeUf = nomeUf;
    }

    public Uf(Integer idUf, String nomeUf, Collection<Cidade> cidades) {
        this.idUf = idUf;
        this.nomeUf = nomeUf;
        this.cidades = cidades;
    }
   
   
    public Integer getIdUf() {
        return this.idUf;
    }
    
    public void setIdUf(int idUf) {
        this.idUf = idUf;
    }
    public String getNomeUf() {
        return this.nomeUf;
    }
    
    public void setNomeUf(String nomeUf) {
        this.nomeUf = nomeUf;
    }

    public Collection<Cidade> getCidades() {
        return cidades;
    }

    public void setCidades(Collection<Cidade> cidades) {
        this.cidades = cidades;
    }
    
}


