/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDeUsuario;

import ControleDeInteracao.ControlePrincipal;

import InterfaceDeUsuario.Advogados.GerenciarAdvogados;
import InterfaceDeUsuario.Advogados.TCadastrarAdvogados;
import InterfaceDeUsuario.Pessoas.GerenciarPessoas;
import InterfaceDeUsuario.Pessoas.TCadPessoa;
import InterfaceDeUsuario.Processos.CadastroProcesso;
import InterfaceDeUsuario.Processos.GerenciarProcesso;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDesktopPane;

/**
 *
 * @author Davy-san
 */
public class Jprincipal extends javax.swing.JFrame implements ActionListener{
    
    TCadPessoa TcadCliente;
    GerenciarPessoas TgerenPessoas;
    CadastroProcesso TcadProcesso;
    GerenciarProcesso TgerenciarProcesso;
    TCadastrarAdvogados TCadAdvogado;
    GerenciarAdvogados genreciarAdvogado;
    /**
     * Creates new form Jprincipal
     */
    public Jprincipal() {
        initComponents();
        ControleDeInteracao.ControlePrincipal CtrlPrincipal = new ControlePrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastroPessoa = new javax.swing.JButton();
        btnCadProcesso = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        btnGerenciarPessoas = new javax.swing.JButton();
        btnGerenciaProcesso = new javax.swing.JButton();
        btnCadAdvogado = new javax.swing.JButton();
        btnGenrenciarAdvogado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadastroPessoa.setText("Cadastro de Pessoa");
        btnCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoaActionPerformed(evt);
            }
        });

        btnCadProcesso.setText("Cadastro de Processo");
        btnCadProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProcessoActionPerformed(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1261, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        btnGerenciarPessoas.setText("Gerenciar Pessoas");
        btnGerenciarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarPessoasActionPerformed(evt);
            }
        });

        btnGerenciaProcesso.setText("Gerencia de Processo");
        btnGerenciaProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciaProcessoActionPerformed(evt);
            }
        });

        btnCadAdvogado.setText("Cadastrar Advogado");
        btnCadAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAdvogadoActionPerformed(evt);
            }
        });

        btnGenrenciarAdvogado.setText("Gerenciar Advogado");
        btnGenrenciarAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenrenciarAdvogadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCadastroPessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerenciarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadProcesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerenciaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenrenciarAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastroPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(btnGerenciarPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerenciaProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadAdvogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenrenciarAdvogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        desktopPane.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoaActionPerformed
        /*if (TcadCliente == null) {
            TcadCliente = new TCadPessoa("Casastro", this);
            desktopPane.add(TcadCliente);
            TcadCliente.setDefaultCloseOperation(HIDE_ON_CLOSE);            
        }
       if(TcadCliente.isClosed()){
            TcadCliente = new TCadPessoa("Casastro", this);
            desktopPane.add(TcadCliente);
            TcadCliente.setDefaultCloseOperation(HIDE_ON_CLOSE); 
        }
        TcadCliente.setVisible(true);
        desktopPane.moveToFront(TcadCliente);*/
        
    }//GEN-LAST:event_btnCadastroPessoaActionPerformed

    private void btnGerenciarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarPessoasActionPerformed
        if(TgerenPessoas == null){
           TgerenPessoas = new GerenciarPessoas("Cadastro", this);
           desktopPane.add(TgerenPessoas);
           TgerenPessoas.setDefaultCloseOperation(HIDE_ON_CLOSE); 
        }
        if(TgerenPessoas.isClosed()){
            TgerenPessoas = new GerenciarPessoas("Cadastro", this);
            desktopPane.add(TgerenPessoas);
            TgerenPessoas.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
       TgerenPessoas.moveToFront();
       TgerenPessoas.setVisible(true);      
    }//GEN-LAST:event_btnGerenciarPessoasActionPerformed

    private void btnGerenciaProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciaProcessoActionPerformed
        if(TgerenciarProcesso == null){
            TgerenciarProcesso = new GerenciarProcesso("Gerenciar Processo", this);
            desktopPane.add(TgerenciarProcesso);
            TgerenciarProcesso.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        if(TgerenciarProcesso.isClosed()){
            TgerenciarProcesso = new GerenciarProcesso("Gerenciar Processo", this);
            desktopPane.add(TgerenciarProcesso);
            TgerenciarProcesso.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        TgerenciarProcesso.moveToFront();
        TgerenciarProcesso.setVisible(true);
    }//GEN-LAST:event_btnGerenciaProcessoActionPerformed

    private void btnCadProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProcessoActionPerformed
         if(TcadProcesso == null){
            TcadProcesso = new CadastroProcesso("Cadastrar Processo", this);
            desktopPane.add(TcadProcesso);
            TcadProcesso.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        if(TcadProcesso.isClosed()){
            TcadProcesso = new CadastroProcesso("Cadastrar Processo", this);
            desktopPane.add(TcadProcesso);
            TcadProcesso.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        TcadProcesso.setVisible(true);           
    }//GEN-LAST:event_btnCadProcessoActionPerformed

    private void btnCadAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAdvogadoActionPerformed
        if(TCadAdvogado == null){
            TCadAdvogado = new TCadastrarAdvogados("Cadastro de Advogados", this);
            desktopPane.add(TCadAdvogado);
            TCadAdvogado.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        if(TCadAdvogado.isClosed()){
            TCadAdvogado = new TCadastrarAdvogados("Cadastro de Advogados", this);
              desktopPane.add(TCadAdvogado);
              TCadAdvogado.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        TCadAdvogado.setVisible(true);
        TCadAdvogado.moveToFront();
    }//GEN-LAST:event_btnCadAdvogadoActionPerformed

    private void btnGenrenciarAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenrenciarAdvogadoActionPerformed
        if(genreciarAdvogado == null){
            genreciarAdvogado = new GerenciarAdvogados("Gerencia de Advogados", this);
            desktopPane.add(genreciarAdvogado);
            genreciarAdvogado.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        if(genreciarAdvogado.isClosed()){
            genreciarAdvogado = new GerenciarAdvogados("Gerencia de Advogados", this);
            desktopPane.add(genreciarAdvogado);
            genreciarAdvogado.setDefaultCloseOperation(HIDE_ON_CLOSE);
        }
        genreciarAdvogado.setVisible(true);
        genreciarAdvogado.moveToFront();
    }//GEN-LAST:event_btnGenrenciarAdvogadoActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAdvogado;
    private javax.swing.JButton btnCadProcesso;
    private javax.swing.JButton btnCadastroPessoa;
    private javax.swing.JButton btnGenrenciarAdvogado;
    private javax.swing.JButton btnGerenciaProcesso;
    private javax.swing.JButton btnGerenciarPessoas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    
}
