/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDeUsuario;

import ControleDeInteracao.ControlePrincipal;

import InterfaceDeUsuario.Advogados.GerenciarAdvogados;
import InterfaceDeUsuario.Advogados.TCadastrarAdvogados;
import InterfaceDeUsuario.Pessoas.GerenciarPessoas;
import InterfaceDeUsuario.Pessoas.TCadPessoa;
import InterfaceDeUsuario.Processos.CadastroProcesso;
import InterfaceDeUsuario.Processos.GerenciarProcesso;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDesktopPane;

/**
 *
 * @author Davy-san
 */
public class Jprincipal extends javax.swing.JFrame implements ActionListener{
    
    TCadPessoa TcadCliente;
    GerenciarPessoas TgerenPessoas;
    CadastroProcesso TcadProcesso;
    GerenciarProcesso TgerenciarProcesso;
    TCadastrarAdvogados TCadAdvogado;
    GerenciarAdvogados genreciarAdvogado;
    
    private ControlePrincipal ctrlPrincipal;
    /**
     * Creates new form Jprincipal
     */
    public Jprincipal(ControlePrincipal ctrlPrincipal) {
        initComponents();
        //ctrlPrincipal = new ControlePrincipal(desktopPane);
        this.ctrlPrincipal = ctrlPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastroPessoa = new javax.swing.JButton();
        btnCadProcesso = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jSeparator2 = new javax.swing.JSeparator();
        btnGerenciarPessoas = new javax.swing.JButton();
        btnGerenciaProcesso = new javax.swing.JButton();
        btnCadAdvogado = new javax.swing.JButton();
        btnGenrenciarAdvogado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadastroPessoa.setText("Cadastro de Pessoa");
        btnCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoaActionPerformed(evt);
            }
        });

        btnCadProcesso.setText("Cadastro de Processo");
        btnCadProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProcessoActionPerformed(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        desktopPane.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 557, Short.MAX_VALUE))
        );

        btnGerenciarPessoas.setText("Gerenciar Pessoas");
        btnGerenciarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarPessoasActionPerformed(evt);
            }
        });

        btnGerenciaProcesso.setText("Gerencia de Processo");
        btnGerenciaProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciaProcessoActionPerformed(evt);
            }
        });

        btnCadAdvogado.setText("Cadastrar Advogado");
        btnCadAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAdvogadoActionPerformed(evt);
            }
        });

        btnGenrenciarAdvogado.setText("Gerenciar Advogado");
        btnGenrenciarAdvogado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenrenciarAdvogadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCadastroPessoa)
                .addGap(6, 6, 6)
                .addComponent(btnGerenciarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnCadProcesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerenciaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenrenciarAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(desktopPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastroPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerenciarPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGerenciaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGenrenciarAdvogado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        desktopPane.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoaActionPerformed
        ctrlPrincipal.AbrirCadastroDePEssoas();
    }//GEN-LAST:event_btnCadastroPessoaActionPerformed

    private void btnGerenciarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarPessoasActionPerformed
        ctrlPrincipal.AbrirGerenciaDePessoas();
    }//GEN-LAST:event_btnGerenciarPessoasActionPerformed

    private void btnGerenciaProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciaProcessoActionPerformed
        ctrlPrincipal.AbrirGerenciaProcesso();
    }//GEN-LAST:event_btnGerenciaProcessoActionPerformed

    private void btnCadProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProcessoActionPerformed
         ctrlPrincipal.AbrirCadastroProcesso();
    }//GEN-LAST:event_btnCadProcessoActionPerformed

    private void btnCadAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAdvogadoActionPerformed
        ctrlPrincipal.AbrirCadastroAdvogado();
    }//GEN-LAST:event_btnCadAdvogadoActionPerformed

    private void btnGenrenciarAdvogadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenrenciarAdvogadoActionPerformed
        ctrlPrincipal.AbriGerenciaAdvogados();
    }//GEN-LAST:event_btnGenrenciarAdvogadoActionPerformed

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAdvogado;
    private javax.swing.JButton btnCadProcesso;
    private javax.swing.JButton btnCadastroPessoa;
    private javax.swing.JButton btnGenrenciarAdvogado;
    private javax.swing.JButton btnGerenciaProcesso;
    private javax.swing.JButton btnGerenciarPessoas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    
}
