/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual.Pessoas;

import Visual.Jprincipal;
import javax.swing.*;

/**
 *
 * @author Davy-san
 */
public class TCadPessoa extends javax.swing.JInternalFrame {
    PainelCadastroPessoaFIsica jpPessoaFisica;
    PainelCadastroPessoaJuridica jpPessoaJuridica;
    /**
     * Creates new form Tela
     */
    public TCadPessoa(String title, Jprincipal janelaP) {
        super(title, true, true, true, true);
        initComponents();
        //this.janelaP = janelaP;
        //janelaP.getDesktopPane().add(this);
        //setVisible(true); 
        //setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPessoa = new javax.swing.ButtonGroup();
        jpPessoas = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnFisica = new javax.swing.JRadioButton();
        rbtnJuridica = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        jpVariavel = new javax.swing.JPanel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 400));

        jpPessoas.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa"));
        jpPessoas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setText("Nome");
        jpPessoas.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 55, -1, -1));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jpPessoas.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 138, 52));

        lblEndereco.setText("Endereço");
        jpPessoas.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 86, -1, -1));
        jpPessoas.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 335, -1));

        lblTel.setText("Telefone");
        jpPessoas.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 116, -1, -1));

        lblEmail.setText("E-mail");
        jpPessoas.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 144, -1, -1));
        jpPessoas.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 335, -1));
        jpPessoas.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 335, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpPessoas.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 142, 52));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroupTipoPessoa.add(rbtnFisica);
        rbtnFisica.setText("FIsica");

        buttonGroupTipoPessoa.add(rbtnJuridica);
        rbtnJuridica.setText("Juridica");
        rbtnJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rbtnFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnJuridica)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFisica)
                    .addComponent(rbtnJuridica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPessoas.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, 40));
        jpPessoas.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 335, -1));

        jpVariavel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpVariavel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addComponent(jpVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if(txtEndereco.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Campo Enderço não preenchido!", "Campo inválido", JOptionPane.WARNING_MESSAGE);
        if(txtEmail.getText().equals(""))
          JOptionPane.showMessageDialog(null, "Campo E-mail não preenchido!", "Campo inválido", JOptionPane.WARNING_MESSAGE);
        if(txtNome.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Campo nome não preenchido!", "Campo inválido", JOptionPane.WARNING_MESSAGE);
        if(txtTel.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Campo telefone não preenchido!", "Campo inválido", JOptionPane.WARNING_MESSAGE);
        
        if(rbtnFisica.isSelected()){
            jpPessoaFisica = new PainelCadastroPessoaFIsica();
            jpVariavel.removeAll();
            jpVariavel.add(jpPessoaFisica);
        }else if(rbtnJuridica.isSelected()){
            jpPessoaJuridica = new PainelCadastroPessoaJuridica();
            jpVariavel.removeAll();
            jpVariavel.add(jpPessoaJuridica);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um tipo de pessoa!", "Erro", JOptionPane.WARNING_MESSAGE);
        }
        jpVariavel.revalidate();
        jpVariavel.repaint();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbtnJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnJuridicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnJuridicaActionPerformed


  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroupTipoPessoa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpPessoas;
    private javax.swing.JPanel jpVariavel;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTel;
    private javax.swing.JRadioButton rbtnFisica;
    private javax.swing.JRadioButton rbtnJuridica;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
