/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDeUsuario.Processos;

import InterfaceDeUsuario.Jprincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Davy-san
 */
public class CadastroProcesso extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroProcesso
     */
    public CadastroProcesso(String titulo) {
        super(titulo, true, true, true, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblJustica = new javax.swing.JLabel();
        lblInstancia = new javax.swing.JLabel();
        lblOrgao = new javax.swing.JLabel();
        lblDistribuido = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblAcao = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblPasta = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtAcao = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtDistribuido = new javax.swing.JTextField();
        cmbJustica = new javax.swing.JComboBox<>();
        cmbInstancia = new javax.swing.JComboBox<>();
        cmbOrgao = new javax.swing.JComboBox<>();
        spnPasta = new javax.swing.JSpinner();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDescricao = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Processo"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setText("Número");
        jPanel1.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 107, -1, -1));

        lblJustica.setText("Justiça");
        jPanel1.add(lblJustica, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 144, -1, -1));

        lblInstancia.setText("Instância");
        jPanel1.add(lblInstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 176, -1, -1));

        lblOrgao.setText("Orgão");
        jPanel1.add(lblOrgao, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 208, -1, -1));

        lblDistribuido.setText("Distribuido");
        jPanel1.add(lblDistribuido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        lblValor.setText("Valor");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        lblDescricao.setText("Descrição");
        jPanel1.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        lblAcao.setText("Ação");
        jPanel1.add(lblAcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        lblEstado.setText("Estado");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        lblTitulo.setText("Titulo");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 36, -1, -1));

        lblPasta.setText("Pasta");
        jPanel1.add(lblPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 73, -1, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 32, 175, -1));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 103, 173, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 32, 97, -1));
        jPanel1.add(txtAcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 173, -1));
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 173, -1));
        jPanel1.add(txtDistribuido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 173, -1));

        jPanel1.add(cmbJustica, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 139, 172, -1));

        jPanel1.add(cmbInstancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 171, 173, -1));

        jPanel1.add(cmbOrgao, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 203, 173, -1));
        jPanel1.add(spnPasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 68, 62, -1));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        txtareaDescricao.setColumns(20);
        txtareaDescricao.setRows(5);
        jScrollPane1.setViewportView(txtareaDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 178, 141));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 10, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String msg = "";
        if(txtTitulo.getText().equals(""))
           msg.concat("Titulo, ");
       // if(spnPasta.get)
        
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbInstancia;
    private javax.swing.JComboBox<String> cmbJustica;
    private javax.swing.JComboBox<String> cmbOrgao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAcao;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDistribuido;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblInstancia;
    private javax.swing.JLabel lblJustica;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblOrgao;
    private javax.swing.JLabel lblPasta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnPasta;
    private javax.swing.JTextField txtAcao;
    private javax.swing.JTextField txtDistribuido;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextArea txtareaDescricao;
    // End of variables declaration//GEN-END:variables
}
